### ISSUE TITLE
fatal: No url found for submodule path

### ISSUE THREAD

**Issue by lpla** [Gekkio/gb-hardware#3]
Hi. I was trying to use this repo as a submodule and got this error:

```
fatal: No url found for submodule path 'GB-BRK-CART/external/kicad-symbols/GB-BENCH-G1/external/gekkio-kicad-libs' in .gitmodules
```

**Comment by Gekkio** [comment]
Looks like something went wrong when I converted the repo to use subtrees instead of submodules...it's fixed now :smile:
